### ISSUE TITLE
search GO:0008054 but return GO:0031145

### ISSUE THREAD

**Issue by ntung** [PRIDE-Utilities/ols-client#22]
Hi,

Recently I have tried to reuse ols-client to resolve cross references name. If I passed GO:0008054, I got  the label GO_0008054 rather than  anaphase-promoting complex-dependent catabolic process. Please take a look at the following test.
`@Test
    public void testGetTermBySecondaryId() throws Exception {
        Term term = olsClient.getTermById(new Identifier("GO:0008054", Identifier.IdentifierType.OBO), "GO");
        System.out.println(term.getLabel());
        //Assert.assertTrue(term.getLabel().equalsIgnoreCase("anaphase-promoting complex-dependent catabolic process"));
    }`

However, if I query this GO term id on OLS site, the result shows that the term is derived/under the other term:  http://purl.obolibrary.org/obo/GO_0031145
It seems to be odd although what we need is **anaphase-promoting complex-dependent catabolic process**.

Do you have any comment on this case?
Thanks and best regards

**Comment by Tobias-Ternent** [comment]
HI @ntung,
I have taken a look into this, and in doing so I found a _different_ problem with looking up by IRI ID, and I've got a fix incoming for that particular problem soon.

When you query for GO:0008054, the request you get from OLS Client is correct - that's exactly what OLS itself is returning, i.e from this query that it executes: http://www.ebi.ac.uk/ols/api/ontologies/go/terms/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FGO_0008054 which has "GO_0008054" as the label.

If you execute that like in a browser, or curl command line, you can see the result in JSON.
 
I think the problem with this particular term is that the term is obsolete, as you can see from the "is_obsolete" field set to "true"....though this information is missing from the Term object in OLS Client. **Would you think it's useful to have this information reported in Term objects if present? If so then I think I can update the Term model class about it.**

Otherwise right now it's possible to get a term's annotation, and see if it has "term replaced by" entries, and then you can query for that entry, e.g.

`Term term = olsClient.getTermById(new Identifier("GO:0008054", Identifier.IdentifierType.OBO), "GO");
if (term.getAnnotation().containsAnnotation("term replaced by")){
	String replacedByUrl =  term.getAnnotation().getAnnotation("term replaced by").get(0);
	replacedByUrl = replacedByUrl.substring(replacedByUrl.lastIndexOf("/")+1);
	replacedByUrl = replacedByUrl.replace("_", ":");
		term = olsClient.getTermById(
		new Identifier(
			replacedByUrl,
			Identifier.IdentifierType.OBO),
		"GO");
	System.out.println(term.getLabel());
}`

Or, alternatively, when the getTermByIRIId() method is fixed as I mentioned above:
`term = olsClient.getTermById(new Identifier("GO:0008054", Identifier.IdentifierType.OBO), "GO");
        if (term.getAnnotation().containsAnnotation("term replaced by")){
            String replacedByUrl =  term.getAnnotation().getAnnotation("term replaced by").get(0);
            term = olsClient.getTermByIRIId( replacedByUrl, term.getOntologyPrefix());
            System.out.println(term.getLabel());
        }`

**Comment by Tobias-Ternent** [comment]
Also I just remembered I think the SPOT team is supposed to be taking care of this library now and they've made recent changes. I might make a pull request with them soon.

**Comment by ntung** [comment]
Hi @Tobias-Ternent,
I think I can resolve the issue based on your answers here. That's really reconstructive and comes in handy. Thanks for that.
